name: Portability Check

on:
  workflow_call:
  push:
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 17 * * 6"

jobs:
  execute:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Execute
        run: |
          python -m penv my_penv
          my_penv\Activate.ps1
          python -m pip install --upgrade pip
          python -m pip install numpy
          Compress-Archive -Path my_penv -DestinationPath my_penv.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my_penv
          path: ./my_penv.zip
  check:
    needs: execute
    runs-on: windows-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: my_penv
          path: .
      - name: Extract Artifact
        run: |
          Expand-Archive -Path my_penv.zip -DestinationPath my_penv
      - name: Check
        run: |
          my_penv\my_penv\Activate.ps1
          echo $env:PATH
          python -c "import numpy;print(numpy.random.randn(5))"
