name: Tests on Push Branches

on:
  push:
    branches:
      - "*"

jobs:
  code-style-check:
    uses: ./.github/workflows/code-style-check-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
  static-type-check:
    uses: ./.github/workflows/static-type-check-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
  pytest:
    uses: ./.github/workflows/pytest-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
  portability-check:
    uses: ./.github/workflows/portability-check-workflow-call.yaml
    with:
      git-ref: ${{ github.ref }}
