name: Scheduled Tests

on:
  schedule:
    - cron: "0 17 * * 6"

jobs:
  code-style-check:
    uses: ./.github/workflows/code-style-check-workflow-call.yaml
  static-type-check:
    uses: ./.github/workflows/static-type-check-workflow-call.yaml
  pytest:
    uses: ./.github/workflows/pytest-workflow-call.yaml
  portability-check:
    uses: ./.github/workflows/portability-check-workflow-call.yaml
