name: Validate Version

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"

jobs:
  validate_version:
    runs-on: ubuntu-latest
    env:
      PRIVATE_REPO_USER: "hmasdev"
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-ref }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Check Version
        run: |
          # Check if the tag is the same as penv.__version__
          export tag=$(echo "$INPUT_GIT_REF" | cut -d / -f 3)
          echo "extracted tag from git-ref: $tag"
          python -c "import os; import penv; assert penv.__version__ == '$tag', (penv.__version__, '$tag')"
        env:
          INPUT_GIT_REF: ${{ inputs.git-ref }}
